### ISSUE TITLE
LabeledObject specification

### ISSUE THREAD

**Issue by NAndreasson** [w3c/webappsec-cowl#49]
Should invoking the LabeledObject constructor enable COWL, in the current context, if not already enabled? Or is it enough to assume that the current confidentiality and integrity labels are empty (as specified by http://w3c.github.io/webappsec-cowl/#framework-context-labels).

Another thing that could potentially be clarified is that reading the protectedObject property on a passed LabeledObject should enable COWL(?), this can be specified in the "context tainting algorithm" - see https://github.com/w3c/webappsec-cowl/issues/48. This is assuming that you can send a LabeledObject to a context where COWL is currently not enabled.

**Comment by deian** [comment]
Good points. Invoking the LabeledObject constructor doesn't need to enable COWL, but we should be consistent and enable COWL when any of the APIs are used.

This includes the protectedObject property (since code should definitely be allowed to send labeled objects to context that haven't yet enabled COWL).
